{
  "id":70,
  "name":"migxresourcerelations_target",
  "formtabs":"[]",
  "contextmenus":"publishtarget||unpublishtarget",
  "actionbuttons":"",
  "columnbuttons":"publishtarget||unpublishtarget",
  "filters":[
    {
      "MIGX_id":2,
      "name":"target_published",
      "label":"published",
      "emptytext":"filter published",
      "type":"combobox",
      "getlistwhere":{
        "rrResourceRelation.published":"[[+target_published]]"
      },
      "getcomboprocessor":"getyesnocombo",
      "combotextfield":"",
      "comboidfield":"",
      "comboparent":""
    }
  ],
  "extended":{
    "migx_add":"",
    "formcaption":"",
    "update_win_title":"",
    "win_id":"relations_target",
    "multiple_formtabs":"",
    "extrahandlers":"this.handlePositionSelector",
    "packageName":"migxresourcerelations",
    "classname":"rrResourceRelation",
    "task":"",
    "getlistsort":"",
    "getlistsortdir":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":1,
    "check_resid":"0",
    "check_resid_TV":"",
    "join_alias":"",
    "getlistwhere":{
      "rrResourceRelation.target_id":"[[+resource_id]]",
      "rrResourceRelation.active":1
    },
    "joins":[
      {
        "alias":"Source",
        "selectfields":"id,pagetitle"
      }
    ],
    "cmpmaincaption":"",
    "cmptabcaption":"",
    "cmptabdescription":"",
    "cmptabcontroller":""
  },
  "columns":[
    {
      "MIGX_id":4,
      "header":"ID",
      "dataIndex":"Source_id",
      "width":10,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    },
    {
      "MIGX_id":1,
      "header":"Pagetitle",
      "dataIndex":"Source_pagetitle",
      "width":20,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"this.renderRowActions",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    },
    {
      "MIGX_id":5,
      "header":"Published",
      "dataIndex":"published",
      "width":10,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"this.renderCrossTick",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    },
    {
      "MIGX_id":6,
      "header":"Position",
      "dataIndex":"pos",
      "width":15,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"this.renderPositionSelector",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    },
    {
      "MIGX_id":7,
      "header":"Image",
      "dataIndex":"imagefield",
      "width":20,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"this.renderChunk",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":[
        {
          "MIGX_id":1,
          "name":"rrRenderImageTVColumn",
          "value":"",
          "clickaction":"",
          "handler":"",
          "image":""
        }
      ]
    },
    {
      "MIGX_id":8,
      "header":"ID",
      "dataIndex":"id",
      "width":10,
      "sortable":"false",
      "show_in_grid":"0",
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    }
  ],
  "createdby":1,
  "createdon":"2013-03-16 06:39:01",
  "editedby":1,
  "editedon":"2013-03-21 05:29:22",
  "deleted":0,
  "deletedon":"-1-11-30 00:00:00",
  "deletedby":0,
  "published":1,
  "publishedon":"2013-03-16 01:00:00",
  "publishedby":0
}