{
  "id":72,
  "name":"migxresourcerelations_pullsources",
  "formtabs":"[]",
  "contextmenus":"",
  "actionbuttons":"",
  "columnbuttons":"activate||deactivate||publishtarget||unpublishtarget",
  "filters":[
    {
      "MIGX_id":1,
      "name":"source_parent",
      "label":"parent",
      "emptytext":"filter Parent",
      "type":"treecombo",
      "getlistwhere":{
        "parent":"[[+source_parent]]"
      },
      "getcomboprocessor":"gettreenode",
      "combotextfield":"pagetitle",
      "comboidfield":"id",
      "comboparent":""
    },
    {
      "MIGX_id":2,
      "name":"source_published",
      "label":"published",
      "emptytext":"filter published",
      "type":"combobox",
      "getlistwhere":{
        "ResourceRelation.published":"[[+source_published]]"
      },
      "getcomboprocessor":"getyesnocombo",
      "combotextfield":"",
      "comboidfield":"",
      "comboparent":""
    },
    {
      "MIGX_id":3,
      "name":"source_active",
      "label":"active",
      "emptytext":"filter active",
      "type":"combobox",
      "getlistwhere":{
        "ResourceRelation.active":"[[+source_active]]"
      },
      "getcomboprocessor":"getyesnocombo",
      "combotextfield":"",
      "comboidfield":"",
      "comboparent":""
    },
    {
      "MIGX_id":4,
      "name":"source_search",
      "label":"search",
      "emptytext":"Search...",
      "type":"textbox",
      "getlistwhere":{
        "pagetitle:LIKE":"%[[+source_search]]%",
        "OR:id:=":"[[+source_search]]"
      },
      "getcomboprocessor":"",
      "combotextfield":"",
      "comboidfield":"",
      "comboparent":""
    }
  ],
  "extended":{
    "migx_add":"",
    "formcaption":"",
    "update_win_title":"",
    "win_id":"relations_pullsources",
    "multiple_formtabs":"",
    "extrahandlers":"",
    "packageName":"migxresourcerelations",
    "classname":"modResource",
    "task":"",
    "getlistsort":"",
    "getlistsortdir":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":1,
    "check_resid":"0",
    "check_resid_TV":"",
    "join_alias":"",
    "getlistwhere":"",
    "joins":[
      {
        "alias":"Parent",
        "selectfields":"id,pagetitle"
      },
      {
        "alias":"ResourceRelation",
        "classname":"rrResourceRelation",
        "on":"ResourceRelation.source_id = modResource.id AND ResourceRelation.target_id =[[+resource_id]]"
      }
    ],
    "cmpmaincaption":"",
    "cmptabcaption":"",
    "cmptabdescription":"",
    "cmptabcontroller":""
  },
  "columns":[
    {
      "MIGX_id":4,
      "header":"ID",
      "dataIndex":"id",
      "renderer":"",
      "sortable":"false",
      "show_in_grid":1
    },
    {
      "MIGX_id":3,
      "header":"Parent",
      "dataIndex":"Parent_pagetitle",
      "width":"",
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    },
    {
      "MIGX_id":1,
      "header":"Pagetitle",
      "dataIndex":"pagetitle",
      "width":"",
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"this.renderRowActions",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    },
    {
      "MIGX_id":2,
      "header":"Active",
      "dataIndex":"ResourceRelation_active",
      "width":"",
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"this.renderCrossTick",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    },
    {
      "MIGX_id":5,
      "header":"Published",
      "dataIndex":"ResourceRelation_published",
      "width":"",
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"this.renderCrossTick",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    },
    {
      "MIGX_id":6,
      "header":"Active",
      "dataIndex":"Joined_active",
      "width":"",
      "sortable":"false",
      "show_in_grid":"0",
      "renderer":"this.renderCrossTick",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    },
    {
      "MIGX_id":7,
      "header":"Published",
      "dataIndex":"published",
      "width":"",
      "sortable":"false",
      "show_in_grid":"0",
      "renderer":"this.renderCrossTick",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    }
  ],
  "createdby":1,
  "createdon":"2013-03-21 10:46:45",
  "editedby":1,
  "editedon":"2013-03-21 10:54:05",
  "deleted":0,
  "deletedon":"-1-11-30 00:00:00",
  "deletedby":0,
  "published":1,
  "publishedon":"2013-03-21 01:00:00",
  "publishedby":0
}